### PR TITLE
Update upload_dbt_models.sql

### PR DESCRIPTION
**Pull request by manojkumarfl**
append =True,

### CODE REVIEW

**Comment by manojkumarfl** [comment]
append=True

**Comment by ofek1weiss** [comment]
Hi @manojkumarfl 
I believe we do not want to use append=True for dbt_models, as it should represent the current status of the models in the project.
Why do you want to change that? is there an issue with that?

**Comment by manojkumarfl** [comment]
Hello.   
In this requirement, we have multiple projects, where  this package "elementary" is used to build audit across all projects.
But unfortunately when we call this package ,  The Audit tables, specifically "DBT_MONITOR"."DBT_MODELS" table is getting Overwritten.   Can we do something about it?

**Comment by manojkumarfl** [comment]
I tried, dispach config, to override upload_dbt_models.sql macro with a custom macro,  but since we are not calling this macro implicitly, and calling the entire package,   we are unable to overwrite.
So ultimately for every elementary package trigger from different projects, the table "DBT_MODELS" audit is getting truncated and loaded

**Comment by ofek1weiss** [comment]
I believe having multiple dbt projects for the same database is not the best practice, and doing something like having separate folders inside a single dbt project and using a `--select` to run each seperatly would be a better approach for you (regardless of elementary, tho it will solve this issue).

If you still have to do it for some reason, then you should try having a separate elementary schema for each project, that way they would not collide.

**Comment by ellakz** [comment]
Hi @manojkumarfl ,
At this point we do not support multiple environments with this setup. In the future we might want to but this will require extensive research on the effects of this on all of our features so we cannot approve this right now. 
I recommend using a different Elementary schema per project.

**Pull request closed without merging**
